<a href="https://colab.research.google.com/github/Jayashree-DataScience/Python_codes/blob/main/Numpy_problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Assignment

Q1. Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.



In [29]:
import numpy as np
def gen_matrix(inp,n,in_b):
  result_matrix=np.vander(x=inp,N=n,increasing=in_b)
  return result_matrix


In [30]:
input_data=np.arange(1,5,1)
n=4
T=True
F=False
matrix_T=gen_matrix(input_data,n,T)
matrix_F=gen_matrix(input_data,n,F)
print("input data is\n",input_data)
print("increasing is True: Resulting Matrix is \n",matrix_T)
print("increasing is False: Resulting Matrix is\n",matrix_F)

input data is
 [1 2 3 4]
increasing is True: Resulting Matrix is 
 [[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
increasing is False: Resulting Matrix is
 [[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


Q2. 

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10


===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1   25 = (10+20+30+40)/4

y2   35 = (20+30+40+50)/4

y3   45 = (30+40+50+60)/4

y4   55 = (40+50+60+70)/4

y5   65 = (50+60+70+80)/4

y6   75 = (60+70+80+90)/4

y7   85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3

In [31]:
import numpy as np

In [32]:
def moving_average(n,i,k):
  cum_sum=np.sum(n,dtype=float)
  print(n)
  cum_avg=cum_sum/k
  return cum_avg

In [33]:
result=[]
input_data=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
k=3
for i in range(0,13):
  if i+k>13:
    break
  input_vector=input_data[i:i+k]
  print("input vector in the loop{}".format(input_vector))
  result_temp=moving_average(input_vector,i,3)
  print("moving average in each iteration {}".format(result_temp))
  result.append(result_temp)
print("------------------------------------\n")
print("Moving Average for the input vector [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] has 11 elements in the sequence (n-k+1=13-3+1=11) \n ")
print(result)

input vector in the loop[3, 5, 7]
[3, 5, 7]
moving average in each iteration 5.0
input vector in the loop[5, 7, 2]
[5, 7, 2]
moving average in each iteration 4.666666666666667
input vector in the loop[7, 2, 8]
[7, 2, 8]
moving average in each iteration 5.666666666666667
input vector in the loop[2, 8, 10]
[2, 8, 10]
moving average in each iteration 6.666666666666667
input vector in the loop[8, 10, 11]
[8, 10, 11]
moving average in each iteration 9.666666666666666
input vector in the loop[10, 11, 65]
[10, 11, 65]
moving average in each iteration 28.666666666666668
input vector in the loop[11, 65, 72]
[11, 65, 72]
moving average in each iteration 49.333333333333336
input vector in the loop[65, 72, 81]
[65, 72, 81]
moving average in each iteration 72.66666666666667
input vector in the loop[72, 81, 99]
[72, 81, 99]
moving average in each iteration 84.0
input vector in the loop[81, 99, 100]
[81, 99, 100]
moving average in each iteration 93.33333333333333
input vector in the loop[99, 100, 150